language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --quiet -r requirements.txt
  - pip install pytest pytest-cov
# command to run tests
script:
  - pytest --cov=./

after_success:
  - codecov